/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package berkasdigital;

//import custom.*;
//import fungsi.akses;
//import simrskhanza.*;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import inventory.DlgCariKonversi;
import inventory.DlgCariObat;
import inventory.DlgCariObat2;
import inventory.DlgCariObat3;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static javax.swing.text.DefaultStyledDocument.ElementSpec.ContentType;
import org.apache.commons.io.FileUtils;
import org.apache.http.HttpVersion;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.mime.MultipartEntity;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.entity.mime.content.ByteArrayBody;
import org.apache.http.entity.mime.content.ContentBody;
import org.apache.http.entity.mime.content.StringBody;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.params.CoreProtocolPNames;
import org.apache.http.util.EntityUtils;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.mozilla.javascript.tools.idswitch.FileBody;
import org.springframework.http.HttpEntity;
import org.apache.pdfbox.multipdf.PDFMergerUtility;
import org.apache.pdfbox.io.MemoryUsageSetting;

/**
 *
 * @author perpustakaan
 */
public class DlgViewPdf extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private String username="",alasanHapus,fileOpen="",LocationFile="";
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public DlgViewPdf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Set ukuran dialog dan frame sesuai A4
        setSize(850, 670);
        internalFrame1.setPreferredSize(new Dimension(850, 670));

        // Override undecorated jika perlu, atau tetap undecorated tapi dengan ukuran fix
        setResizable(true);  // Biar bisa di-resize manual jika diperlukan

        // Letakkan di tengah layar
        setLocationRelativeTo(null);

        txtLokasiFile.setVisible(false);
        txtNoRawat.setVisible(false);

        //TCatatan.setText(TCatatan);
//        TCatatan.setLineWrap(true);
//        TCatatan.setWrapStyleWord(true);
//        status.setVisible(false);


    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelGlass8 = new widget.panelisi();
        BtnViewFile = new widget.Button();
        BtnMergePDF = new widget.Button();
        BtnKeluar = new widget.Button();
        txtNameFile = new widget.TextBox();
        txtLokasiFile = new widget.TextBox();
        txtNoRawat = new widget.TextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Dokumen Signature PDF ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(70, 70, 70))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(169, 83));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        internalFrame1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(160, 56));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        BtnViewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search.png"))); // NOI18N
        BtnViewFile.setMnemonic('S');
        BtnViewFile.setText("View");
        BtnViewFile.setToolTipText("Alt+S");
        BtnViewFile.setName("BtnViewFile"); // NOI18N
        BtnViewFile.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnViewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewFileActionPerformed(evt);
            }
        });
        BtnViewFile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnViewFileKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnViewFile);

        BtnMergePDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnMergePDF.setMnemonic('S');
        BtnMergePDF.setText("Gabungkan PDF");
        BtnMergePDF.setToolTipText("Alt+S");
        BtnMergePDF.setName("BtnMergePDF"); // NOI18N
        BtnMergePDF.setPreferredSize(new java.awt.Dimension(150, 30));
        BtnMergePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMergePDFActionPerformed(evt);
            }
        });
        BtnMergePDF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnMergePDFKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnMergePDF);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/cross.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        txtNameFile.setEditable(false);
        txtNameFile.setName("txtNameFile"); // NOI18N
        txtNameFile.setPreferredSize(new java.awt.Dimension(200, 24));
        txtNameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameFileActionPerformed(evt);
            }
        });
        panelGlass8.add(txtNameFile);

        txtLokasiFile.setEditable(false);
        txtLokasiFile.setName("txtLokasiFile"); // NOI18N
        txtLokasiFile.setPreferredSize(new java.awt.Dimension(200, 24));
        txtLokasiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiFileActionPerformed(evt);
            }
        });
        panelGlass8.add(txtLokasiFile);

        txtNoRawat.setEditable(false);
        txtNoRawat.setName("txtNoRawat"); // NOI18N
        txtNoRawat.setPreferredSize(new java.awt.Dimension(200, 24));
        txtNoRawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoRawatActionPerformed(evt);
            }
        });
        panelGlass8.add(txtNoRawat);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnViewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewFileActionPerformed
    if(Sequel.cariInteger("select count(nama_file) from berkas_tte where nama_file='"+txtNameFile.getText()+"'")>0){
       LocationFile="server"; 
       setButton(false);
       deleteFile();
    }else{
       setButton(true);
       LocationFile="local"; 
    }
    viewpdf(txtNameFile.getText(),LocationFile); 
}//GEN-LAST:event_BtnViewFileActionPerformed
void viewpdf(String fileName,String fileLocation){
          try {
                //HttpPost postRequest = new HttpPost("http://"+koneksiDB.HOSTHYBRIDWEB()+":"+koneksiDB.PORTWEB()+"/"+koneksiDB.HYBRIDWEB()+"/berkastte/upload.php?doc="+docpath);
                SwingController ctrl = new SwingController();
                SwingViewBuilder vb = new SwingViewBuilder(ctrl);
                JPanel s = vb.buildViewerPanel();
                ComponentKeyBinding.install(ctrl, s);
                ctrl.setToolBarVisible(false);
                ctrl.getDocumentViewController().setAnnotationCallback(
                new org.icepdf.ri.common.MyAnnotationCallback(ctrl.getDocumentViewController())
                );
                if(fileLocation.equals("local")){  
                  ctrl.openDocument("tempfile/"+txtNameFile.getText());
                }else{
                 URL url =new URL("http://"+koneksiDB.HOSTHYBRIDWEB()+ ":" + koneksiDB.PORTWEB() + "/"+koneksiDB.HYBRIDWEB()+"/"+txtLokasiFile.getText()+"/"+txtNameFile.getText());
                   ctrl.openDocument(url);
                }
              jScrollPane1.setViewportView(s); 
        }
        catch (Exception e){
            
        }
}
    void openpdf(String file){
          try {
            URL url =new URL("http://"+koneksiDB.HOSTHYBRIDWEB()+ ":" + koneksiDB.PORTWEB() + "/"+koneksiDB.HYBRIDWEB()+"/"+txtLokasiFile.getText()+"/"+file);
            SwingController ctrl = new SwingController();
            SwingViewBuilder vb = new SwingViewBuilder(ctrl);
            JPanel s = vb.buildViewerPanel();
            s.setPreferredSize(new Dimension(400, 243));
            s.setMaximumSize(new Dimension(400, 243));
            ComponentKeyBinding.install(ctrl, s);
            ctrl.setToolBarVisible(false);
            ctrl.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(ctrl.getDocumentViewController())
            );
            ctrl.openDocument(url);
            jScrollPane1.setViewportView(s);
        } catch (Exception e) {
            
        }
}
    private void BtnViewFileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnViewFileKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            BtnViewFileActionPerformed(null);
        }else{
//            Valid.pindah(evt,TCatatan,BtnKeluar);
        }
}//GEN-LAST:event_BtnViewFileKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
      dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//        TCatatan.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void txtNameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameFileActionPerformed

    private void txtLokasiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiFileActionPerformed

    private void BtnMergePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMergePDFActionPerformed
        if (txtNoRawat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tidak ada data berkas untuk digabungkan!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try {
            String noRawat = txtNoRawat.getText();
            String pathFile = txtLokasiFile.getText();
            String noRawatFormatted = noRawat.replaceAll("/", "_");

            // Urutan jenis berkas sesuai kebutuhan
            String[] jenisBerkas = {
                "SEP_",
                "Gruper_",
                "Resume_",
                "RiwayatPerawatan_",
                "SKDP_",
                "SPRI_",
                "Awal_Medis_IGD_",
                "Triase_",
                "Lab_",
                "Radiologi_",
                "Billing_"
            };

            // List untuk menyimpan file PDF yang berhasil didownload
            java.util.List<File> pdfFiles = new java.util.ArrayList<>();
            File tempDir = new File("tempfile");
            if (!tempDir.exists()) {
                tempDir.mkdirs();
            }

            // Download semua PDF yang tersedia
            for (String jenis : jenisBerkas) {
                // File dari bridging BPJS/Kemenkes tidak perlu signed (sudah sah dari sumber)
                String fileName;
                if (jenis.equals("SEP_") || jenis.equals("Gruper_") || jenis.equals("SKDP_")) {
                    fileName = jenis + noRawatFormatted + ".pdf";  // Tanpa _signed
                } else {
                    fileName = jenis + noRawatFormatted + "_signed.pdf";  // Dengan _signed untuk TTe
                }

                try {
                    URL url = new URL("http://" + koneksiDB.HOSTHYBRIDWEB() + ":" + koneksiDB.PORTWEB() + "/" + koneksiDB.HYBRIDWEB() + "/" + pathFile + "/" + fileName);

                    // Cek apakah file ada
                    java.net.HttpURLConnection connection = (java.net.HttpURLConnection) url.openConnection();
                    connection.setRequestMethod("HEAD");
                    connection.connect();

                    if (connection.getResponseCode() == 200) {
                        // Download file
                        File tempFile = new File(tempDir, fileName);
                        FileUtils.copyURLToFile(url, tempFile);
                        pdfFiles.add(tempFile);
                        System.out.println("Downloaded: " + fileName);
                    }
                    connection.disconnect();
                } catch (Exception e) {
                    System.out.println("Skip file: " + fileName);
                }
            }

            if (pdfFiles.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Tidak ada file PDF yang ditemukan untuk digabungkan!",
                    "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                this.setCursor(Cursor.getDefaultCursor());
                return;
            }

            // Merge PDF menggunakan PDFBox
            org.apache.pdfbox.multipdf.PDFMergerUtility pdfMerger = new org.apache.pdfbox.multipdf.PDFMergerUtility();

            for (File pdfFile : pdfFiles) {
                pdfMerger.addSource(pdfFile);
            }

            // Nama file hasil merge
            String mergedFileName = "Gabungan_Berkas_" + noRawatFormatted + ".pdf";
            File mergedFile = new File(tempDir, mergedFileName);
            pdfMerger.setDestinationFileName(mergedFile.getAbsolutePath());

            // Lakukan merge
            pdfMerger.mergeDocuments(org.apache.pdfbox.io.MemoryUsageSetting.setupMainMemoryOnly());

            JOptionPane.showMessageDialog(this,
                "Berkas berhasil digabungkan!\n" +
                "Total: " + pdfFiles.size() + " file\n" +
                "Lokasi: " + mergedFile.getAbsolutePath(),
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);

            // Tampilkan hasil merge
            txtNameFile.setText(mergedFileName);
            viewpdf(mergedFileName, "local");

            // Hapus file temporary setelah merge (optional)
            // for (File pdfFile : pdfFiles) {
            //     pdfFile.delete();
            // }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error saat menggabungkan PDF: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            this.setCursor(Cursor.getDefaultCursor());
        }
    }//GEN-LAST:event_BtnMergePDFActionPerformed

    private void BtnMergePDFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnMergePDFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMergePDFKeyPressed

    private void txtNoRawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoRawatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoRawatActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgViewPdf dialog = new DlgViewPdf(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnMergePDF;
    private widget.Button BtnViewFile;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private widget.panelisi panelGlass8;
    private widget.TextBox txtLokasiFile;
    private widget.TextBox txtNameFile;
    private widget.TextBox txtNoRawat;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
//        Sequel.cariIsi("select nm_pasien from pasien where no_rkm_medis=? ",TPasien,TNoRM.getText());
    }

    
    
    
    public void isCek(){
        BtnViewFile.setEnabled(true);

       
        
    }
public void tampilPdf(String namFile,String pathFile)
{
     txtNameFile.setText(namFile);
     txtLokasiFile.setText(pathFile);
        openpdf(namFile);
 
    

}
public void tampilPdf2(String namFile)
{
     txtNameFile.setText(namFile);
        openpdf(namFile);
 
    

}
public void tampilPdfLocal(String namFile,String Location,String pathFile,String NoRawat)
{
     txtNameFile.setText(namFile);
     txtLokasiFile.setText(pathFile);
     txtNoRawat.setText(NoRawat);
     viewpdf(namFile,Location);
 

}
public void setButton(Boolean BtnTTE)
{

}

void deleteFile(){
       File file = new File("tempfile");
        String[] myFiles;
        if (file.isDirectory()) {
            myFiles = file.list();
            for (int i = 0; i < myFiles.length; i++) {
                File myFile = new File(file, myFiles[i]);
                myFile.delete();
            }
        }
   }

public void tampilMultiplePdf(String noRawat, String pathFile) {
    try {
        // Format no_rawat untuk nama file
        String noRawatFormatted = noRawat.replaceAll("/", "_");

        // Urutan jenis berkas sesuai kebutuhan
        String[] jenisBerkas = {
            "SEP_",
            "Gruper_",
            "Resume_",
            "RiwayatPerawatan_",
            "SKDP_",
            "SPRI_",
            "Awal_Medis_IGD_",
            "Triase_",
            "Lab_",
            "Radiologi_",
            "Billing_"
        };

        // Panel container untuk multiple PDF
        javax.swing.JPanel containerPanel = new javax.swing.JPanel();
        containerPanel.setLayout(new javax.swing.BoxLayout(containerPanel, javax.swing.BoxLayout.Y_AXIS));

        int pdfCount = 0;

        // Loop untuk setiap jenis berkas
        for (String jenis : jenisBerkas) {
            // File dari bridging BPJS/Kemenkes tidak perlu signed (sudah sah dari sumber)
            String fileName;
            if (jenis.equals("SEP_") || jenis.equals("Gruper_") || jenis.equals("SKDP_")) {
                fileName = jenis + noRawatFormatted + ".pdf";  // Tanpa _signed
            } else {
                fileName = jenis + noRawatFormatted + "_signed.pdf";  // Dengan _signed untuk TTe
            }

            try {
                // Cek apakah file ada di server
                URL url = new URL("http://" + koneksiDB.HOSTHYBRIDWEB() + ":" + koneksiDB.PORTWEB() + "/" + koneksiDB.HYBRIDWEB() + "/" + pathFile + "/" + fileName);

                // Coba buka koneksi untuk cek file exists
                java.net.HttpURLConnection connection = (java.net.HttpURLConnection) url.openConnection();
                connection.setRequestMethod("HEAD");
                connection.connect();

                if (connection.getResponseCode() == 200) {
                    // File ada, buat viewer untuk PDF ini
                    SwingController ctrl = new SwingController();
                    SwingViewBuilder vb = new SwingViewBuilder(ctrl);
                    JPanel pdfPanel = vb.buildViewerPanel();
                    ComponentKeyBinding.install(ctrl, pdfPanel);
                    ctrl.setToolBarVisible(false);
                    ctrl.getDocumentViewController().setAnnotationCallback(
                        new org.icepdf.ri.common.MyAnnotationCallback(ctrl.getDocumentViewController())
                    );
                    ctrl.openDocument(url);

                    // Set ukuran panel
                    pdfPanel.setPreferredSize(new java.awt.Dimension(850, 800));
                    pdfPanel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 800));

                    // Tambahkan separator jika bukan PDF pertama
                    if (pdfCount > 0) {
                        containerPanel.add(new javax.swing.JSeparator());
                    }

                    // Tambahkan label nama berkas
                    javax.swing.JLabel label = new javax.swing.JLabel(jenis.replace("_", " ") + noRawat);
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
                    label.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
                    containerPanel.add(label);

                    // Tambahkan PDF panel
                    containerPanel.add(pdfPanel);
                    pdfCount++;
                }
                connection.disconnect();
            } catch (Exception e) {
                // File tidak ada atau error, skip ke file berikutnya
                System.out.println("File tidak ditemukan: " + fileName);
            }
        }

        if (pdfCount > 0) {
            // Tampilkan semua PDF yang ditemukan
            jScrollPane1.setViewportView(containerPanel);
            txtLokasiFile.setText(pathFile);
            txtNoRawat.setText(noRawat);
        } else {
            // Tidak ada PDF yang ditemukan
            JOptionPane.showMessageDialog(this,
                "Tidak ada berkas PDF yang ditemukan untuk No. Rawat: " + noRawat,
                "Informasi",
                JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error saat memuat berkas: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
}


}
